[project]
id = "fg-j.sample.dotnet-develop"
name = "Dotnet App Development Container"
version = "0.0.1"

[build]

[[build.buildpacks]]
uri = "docker://paketobuildpacks/dotnet-core-runtime:latest"

[[build.buildpacks]]
uri = "docker://paketobuildpacks/dotnet-core-aspnet:latest"

[[build.buildpacks]]
uri = "docker://paketobuildpacks/dotnet-core-sdk:latest"

[[build.buildpacks]]
uri = "docker://paketobuildpacks/icu:latest"

[[build.buildpacks]]
uri = "gcr.io/paketo-buildpacks/procfile"

[[build.buildpacks]]
uri = "gcr.io/paketo-community/build-plan"
